#!/usr/bin/env python

import logging

log = logging.getLogger("test-package")
options = None
basic_packages = ["app-portage/gentoolkit"]
default_profile = "default/linux/amd64/17.0"


def massage_string(string):
    """Return a string."""

    import sys

    if sys.version_info[0] < 3:
        return string
    else:
        return string.decode("UTF-8")


class Docker:

    def __init__(self, local_portage, overlay_dirs):
        """Create a new container."""

        import os.path

        docker_image = "gentoo/stage3-amd64"
        overlay_dirs = list(set(overlay_dirs))
        overlay_mountpoints = [os.path.join("/var/lib/overlays", p)
                               for p in map(os.path.basename, overlay_dirs)]

        self._setup_container(docker_image)
        self._create_container(docker_image, local_portage,
                               zip(overlay_dirs, overlay_mountpoints))
        self._start_container()
        self._set_profile()
        self._tweak_settings()
        self._enable_overlays(map(os.path.basename, overlay_dirs))
        self._unmask_atom()
        self._unmask()
        self._update()
        self._install_basics()
        self._set_gcc()
        self._print_summary()

    def execute(self, cmd):
        """Execute command in container.

        cmd is a string which is executed within a bash shell.
        """

        import os
        import subprocess
        import sys

        global log

        log.info("%s %s" % (self.cid[:6], cmd))
        docker_cmd = ["docker", "exec", "--interactive"]
        docker_cmd += [self.cid, "/bin/bash"]
        docker = subprocess.Popen(docker_cmd,
                                  stdout=subprocess.PIPE,
                                  stderr=subprocess.PIPE,
                                  stdin=subprocess.PIPE,
                                  universal_newlines=True)
        docker.stdin.write(cmd + "\n")
        docker.stdin.close()
        stdout_reader = os.fork()
        if stdout_reader == 0:
            self._reader(docker, docker.stdout, "stdout")
            sys.exit(0)
        stderr_reader = os.fork()
        if stderr_reader == 0:
            self._reader(docker, docker.stderr, "stderr")
            sys.exit(0)
        os.waitid(os.P_PID, stdout_reader, os.WEXITED)
        os.waitid(os.P_PID, stderr_reader, os.WEXITED)
        docker.wait()
        if docker.returncode != 0:
            log.error("running in container %s" % (str(self.cid)))
            raise Exception("failed command \"%s\"" % (cmd))

    def shell(self):
        """Run an interactive shell in container."""

        import subprocess

        global log

        log.info("running interactive shell in container")
        docker = subprocess.Popen(["docker", "exec", "--tty", "--interactive",
                                   self.cid, "/bin/bash"])
        docker.wait()

    def _reader(self, proc, stream, name):
        """Read from a subprocess stream."""

        global log
        global log_ch

        while True:
            out = stream.readline()
            if out == "" and proc.poll() is not None:
                break
            log.info("%s (%s): %s" % (self.cid[:6], name, out.rstrip()))
            log_ch.flush()

    def _setup_container(self, docker_image):
        """Setup the container."""

        import subprocess

        docker_args = ["docker", "pull", docker_image]
        docker = subprocess.Popen(docker_args)
        docker.wait()

    def _create_container(self, docker_image, local_portage, overlays):
        """Create new container."""

        import subprocess

        docker_args = [
            "docker", "create",
            "--tty",
            "--cap-add", "SYS_ADMIN",
            "--device", "/dev/fuse",
            "--storage-opt", "size=50G",
            "--workdir", "/root",
            "--volume", "%s:/usr/portage" % local_portage,
            "--volume", "/usr/portage/distfiles:/usr/portage/distfiles"]
        for o in overlays:
            docker_args += ["--volume=%s:%s" % o]
        docker_args += [docker_image]
        log.info("creating docker container with: %s" %
                 " ".join(docker_args))
        docker = subprocess.Popen(docker_args, stdout=subprocess.PIPE)
        docker.wait()
        if docker.returncode != 0:
            raise Exception("failure creating docker container")

        lines = docker.stdout.readlines()
        if len(lines) > 1:
            raise Exception("more output than expected")
        self.cid = massage_string(lines[0]).strip()
        log.info("container id %s" % (self.cid))

    def _start_container(self):
        """Start the container."""

        import subprocess

        docker_args = ["docker", "start", "%s" % self.cid]
        docker = subprocess.Popen(docker_args, stdout=subprocess.PIPE)
        docker.wait()
        if docker.returncode != 0:
            raise Exception("failure creating docker container")

    def _set_profile(self):
        """Set the Gentoo profile."""

        log.info("setting Gentoo profile to %s" % default_profile)
        self.execute("eselect profile set %s" % default_profile)

    def _tweak_settings(self):
        """Tweak portage settings."""

        log.info("tweaking portage settings")

        # Disable the usersandbox feature, it's not working well inside a
        # docker container.
        self.execute("echo FEATURES=\\\"-sandbox -usersandbox\\\" " +
                     ">> /etc/portage/make.conf")
        self.execute("echo MAKEOPTS=\\\"-j{}\\\" ".format(options.threads) +
                     ">> /etc/portage/make.conf")

    def _enable_overlays(self, overlays):
        """Enable overlays."""

        self.execute("mkdir -p /etc/portage/repos.conf")
        for o in overlays:
            self.execute("echo \"[%s]\" >> "
                         "/etc/portage/repos.conf/overlays.conf" % o)
            self.execute("echo \"location = /var/lib/overlays/%s\" >> "
                         "/etc/portage/repos.conf/overlays.conf" % o)
            self.execute("echo \"master = gentoo\" >> "
                         "/etc/portage/repos.conf/overlays.conf")

    def _unmask_atom(self):
        """Unmask the atom to install."""

        log.info("unmasking atom")
        if options.atom is not None:
            for a in options.atom:
                self.execute(
                    "echo \"" + a + "\" ** >> " +
                    "/etc/portage/package.accept_keywords")

    def _unmask(self):
        """Unmask other atoms."""

        log.info("unmasking additional atoms")
        for a in options.unmask:
            log.info("  unmasking %s" % a)
            self.execute(
                "echo \"%s\" ~amd64 >> /etc/portage/package.accept_keywords" %
                a)

    def _set_ebuild_use_flag(self, ebuild, use):
        """Set the USE flags for a particular ebuild.

        ebuild is a string and use is a list of strings.
        """

        self.execute("echo %s %s >> /etc/portage/package.use/testbuild" %
                     (ebuild, " ".join(use)))

    def _set_use_flags(self):
        """Set USE flags on ebuild."""

        self._set_ebuild_use_flag("git", ["curl"])
        if options.atoms is not None and len(options.use) > 0:
            for a in options.atom:
                self._set_ebuild_use_flag(a, options.use)

    def _update(self):
        """Update container."""

        if not options.update:
            log.info("skipping update")
        else:
            log.info("updating container")
            self.execute("emerge --verbose --update --deep --newuse @world")

    def _install_basics(self):
        """Install some basic packages."""

        log.info("installing basic packages: " + ", ".join(basic_packages))
        for p in basic_packages:
            log.info("  installing %s" % p)
            self.execute("emerge --verbose %s" % p)

    def _set_gcc(self):
        """Set gcc in the container."""

        import re

        log.info("setting gcc")
        if options.gcc_version:
            self.execute(
                ("echo =sys-devel/gcc-%s ** >> " % options.gcc_version) +
                "/etc/portage/package.accept_keywords")
            self.execute("emerge --verbose sys-devel/gcc")
            gcc = re.sub("-r[0-9]+$", "", options.gcc_version)
            self.execute("gcc-config $(gcc-config --list-profiles | " +
                         ("grep %s | " % gcc) +
                         "sed -e 's:^.*\[\([0-9]\+\)\].*:\\1:')")
            self.execute("emerge --verbose --oneshot sys-devel/libtool")

    def _print_summary(self):
        """Print summary."""

        log.info("summary")
        self.execute("if [[ -f /etc/portage/accept_keywords ]]; then " +
                     "cat /etc/portage/package.accept_keywords; fi")
        self.execute("if [[ -f /etc/portage/package.use/testbuild ]]; then " +
                     "cat /etc/portage/package.use/testbuild; fi")
        self.execute("emerge --info")


def parse_commandline():
    """Parse the command line."""

    import argparse

    global options

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--atom",
        help="The package atom(s) to install",
        nargs="+",
        action="append")
    parser.add_argument(
        "--manual",
        help="Install package manually",
        default=False,
        action="store_true")
    parser.add_argument(
        "--portage-dir",
        help="The local portage directory",
        required=True)
    parser.add_argument(
        "--overlay-dir",
        help="Add overlay dir (can be used multiple times)",
        action="append",
        default=[])
    parser.add_argument(
        "--update",
        help="Update container before installing atom",
        default=False,
        action="store_true")
    parser.add_argument(
        "--threads",
        metavar="N",
        help="Use N threads to build packages",
        default=1,
        type=int)
    parser.add_argument(
        "--use",
        help="The use flags for the atom",
        default=[],
        nargs="+")
    parser.add_argument(
        "--unmask",
        metavar="ATOM",
        help="Unmask atom (can be used multiple times)",
        default=[],
        action="append")
    parser.add_argument(
        "--gcc-version",
        metavar="VER",
        help="Use gcc version VER")
    parser.add_argument(
        "--with-X",
        help="Install VNC server to test graphical applications",
        default=False,
        action="store_true")
    options = parser.parse_args()

    if not options.manual and options.atom is None:
        raise Exception("either specify an atom or use --manual")

    if options.atom:
        temp = []
        for a in options.atom:
            temp += a
        options.atom = temp
    else:
        options.atom = []

    if options.with_X:
        options.atom += ["net-misc/tigervnc", "x11-wm/icewm"]


def main():
    """The main function."""

    import os.path

    global log
    global log_ch
    global options

    log.setLevel(logging.DEBUG)

    log_ch = logging.StreamHandler()
    log_ch.setLevel(logging.INFO)
    log_ch.setFormatter(logging.Formatter("%(asctime)s - %(message)s"))
    log.addHandler(log_ch)

    fh = logging.FileHandler("tester.log", "a")
    fh.setLevel(logging.INFO)
    fh.setFormatter(logging.Formatter("%(asctime)s - %(message)s"))
    log.addHandler(fh)

    parse_commandline()

    log.info("creating container")
    container = Docker(
        os.path.abspath(os.path.expanduser(options.portage_dir)),
        [os.path.abspath(p) for p in options.overlay_dir])

    log.info("created container " + container.cid)
    if options.manual:
        container.shell()
    else:
        container.execute("echo emerge --ask --autounmask-write=n --verbose " +
                          " ".join(options.atom) +
                          " >> ~/.bash_history")
        try:
            container.execute("emerge --autounmask-write=n --verbose " +
                              " ".join(options.atom))
        except Exception:
            log.warn("ignoring failure of command")
        container.execute("etc-update --automode -5")
        try:
            container.execute("emerge --verbose " + " ".join(options.atom))
        except Exception:
            log.warn("ignoring failure of command")
        container.shell()


if __name__ == "__main__":
    main()
else:
    raise Exception("can not be imported")
